name: ⚙️ Bug Report 🪛
description: Report a bug 🪲
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for making this bug report.

        ⚠️ Mind your title. ⚠️

        - "chart stuck in deploying state" - Is not the title/description of your actual bug.
        - "chartname not working" - Is not the title/description of your actual bug.
        - Don't refer version in title.
        - Always prefix an issue with `[chart-name]`

        ---

  - type: input
    id: chart-name
    attributes:
      label: Chart Name
      description: |
        The name of the chart having the issue.
    validations:
      required: true
  - type: dropdown
    id: os-version
    attributes:
      label: Operating System
      description: |
        The type and version of the operating system you are currently running.
      multiple: false
      options:
        - "Talos-OS 1.7"
        - "Talos-OS 1.6"
        - "Talos-OS 1.5"
        - "other"
    validations:
      required: true
  - type: dropdown
    id: deployment-method
    attributes:
      label: Deployment Method
      description: |
        Please select how your deployed the Chart in question
      multiple: false
      options:
        - "Helm"
        - "KubeApps"
        - "FluxCD"
        - "Rancher"
        - "ArgoCD"
    validations:
      required: true
  - type: input
    id: chart-version
    attributes:
      label: Chart Version
      description: |
        The version of the chart having the issue and versions of any charts being used in conjunction.
    validations:
      required: true
  - type: textarea
    id: chart-events
    attributes:
      label: Kubernetes Events
      description: |
        Debug information from the chart(s) specifically
      render: Shell
    validations:
      required: true
  - type: textarea
    id: chart-logs
    attributes:
      label: Chart Logs
      description: |
        Log output from the containers involved in the chart
      render: Shell
    validations:
      required: true
  - type: textarea
    id: chart-config
    attributes:
      label: Chart Configuration
      description: |
        The configuration settings for the chart.
        For Helm: your custom values.yaml file
    validations:
      required: true
  - type: textarea
    id: bug-report
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: To Reproduce
      description: |
        Make sure that if you follow these steps again yourself the bug hchartens again. If it doesn't it's Probably a configuration error and should be handled with a support ticket on the discord.
        Steps to reproduce the behavior:
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error.
    validations:
      required: true
  - type: textarea
    id: exp-behaviour
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to hcharten.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If chartlicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: textarea
    id: add-contaxt
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: I've read and agree with the following
      options:
        - label: I've checked all open and closed issues and my issue is not there.
          required: true
        - label: I've understand TrueNAS SCALE Apps are deprecated and TrueCharts does not accept TrueNAS SCALE related issues
          required: true
        - label: I've prefixed my issue title with `[Chart-Name]`
          required: true
