name: ⚙️ Report Outdated App 🪛
description: Report a Outdated App
labels: ["outdated"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for making this bug report.
        
        - Chart version, means **our** version
        - Apps in the *incubator* train, **CANNOT be reported as outdated**, as they might not even be functional at all
        - Apps in the *stable* train, can be reported after the container update is at least **1 month old**
        - Apps in the *premium* and *system* trains, can be reported after the container update is **at least 7 days old**
        ---

  - type: input
    id: app-name
    attributes:
      label: App Name
      description: |
        The name of the app having the issue.
    validations:
      required: true
  - type: dropdown
    id: os-version
    attributes:
      label: Operating System
      description: |
        The type and version of the operating system you are currently running.
      multiple: false
      options:
        - "Talos-OS 1.9"
        - "Talos-OS 1.8"
        - "Talos-OS 1.7"
        - "other"
    validations:
      required: true
  - type: dropdown 
    id: train
    attributes:
      label: Train Name
      description: |
        The Train the outdated Chart is in.
      multiple: false
      options:
        - "incubator"
        - "stable"
        - "premium"
        - "system"
    validations:
      required: true
  - type: input
    id: chart-version
    attributes:
      label: Chart Version
      description: |
        The version of the chart beeing outdated.
    validations:
      required: true
  - type: input
    id: latest-container
    attributes:
      label: Latest Available Container Version
      description: |
        The version of the latest released upstream container
    validations:
      required: true
  - type: input
    id: latest-container-link
    attributes:
      label: Link to container
      description: |
        Link to the container
    validations:
      required: true
  - type: textarea
    id: add-contaxt
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: I've read and agree with the following
      options:
        - label: I've checked all open and closed issues and my issue is not there.
          required: true
        - label: I confirm that this chart is outdated for at least 7 days (premium/system train) or 1 month (stable train).
          required: true
        - label: I confirm that this is not an incubator chart.
          required: true
